
name: CI

on:
  push:

jobs:
  php-tests:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      matrix:
        php: [7.4, 8.0]
        experimental: [ false ]
        include:
          - php: 8.1
            experimental: true

    name: PHP${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json

      - name: Install dependencies
        run: composer update --prefer-dist --no-suggest --no-interaction --ignore-platform-reqs --no-scripts

#      - name: Check codestyle
#        run: vendor/bin/ecs check --config=easy-coding-standard.yml --no-progress-bar .

      - name: Execute tests
        run: vendor/bin/phpunit --testdox --colors=always
